name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # No correr postinstall y NO instalar opcionales (salteamos "printer")
      - name: Install deps (clean, no lifecycle, omit optional)
        run: npm ci --ignore-scripts --omit=optional

      # Rebuild nativos para Electron (best-effort) usando bash
      - name: Rebuild native modules
        shell: bash
        run: npx electron-rebuild -f --which-module "escpos-usb,usb,escpos-network" || true

      # Desactivar npmRebuild de electron-builder para que NO intente 'npm rebuild printer'
      - name: Build Windows (NSIS)
        run: npx electron-builder -w --publish=never --config.npmRebuild=false

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe
