name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Rebuild native modules
        run: npx electron-rebuild -f -w escpos-usb -w usb -w escpos-network || echo ok

      - name: Build Windows (NSIS)
        run: npx electron-builder -w --publish=never

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe
