name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Evitar que corra tu postinstall (rebuild-usb.js) en CI
      - name: Install deps (clean, no lifecycle)
        run: npm ci --ignore-scripts

      # FIX: un solo --which-module, y ejecutarlo con bash para que funcione "|| true"
      - name: Rebuild native modules (best-effort)
        shell: bash
        run: npx electron-rebuild -f --which-module "escpos-usb,usb,escpos-network" || true

      - name: Build Windows (NSIS)
        run: npx electron-builder -w --publish=never

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe
